### ISSUE TITLE
[BUG] - new_targets_tf = tf.ones((78,1)) in Attribution methods of regression model

### ISSUE THREAD

**Issue by survivebycoding** [deel-ai/xplique#108]
**Select the modules to which the bug refers:**

- [*] Attributions Methods
- [ ] Feature Visualization
- [ ] Concepts
- [ ] Metrics 
- [ ] Documentation

**Describe the bug**

**Screenshots**
If applicable, add screenshots to help explain your problem. Especially, if you have an error please provide the complete logs.

**Desktop (please complete the following information):**
 - OS
 - Python version
 - Tensorflow version
 - Packages used version (PyTorch, Numpy, scikit-learn, etc..)

**To Reproduce**
Steps to reproduce the behavior. Even better if you can provide a **minimal** working example to
 reproduce the behavior or example of code to reproduce the bug.

**Expected behavior**

**Additional context**
Suppose the regression has 5 outputs (multi-output regression), will new_targets_tf = tf.ones((78,1)) change to new_targets_tf = tf.ones((78,5)) in such a case?

**Comment by AntoninPoche** [comment]
If 78 is your number and samples and 5 the number of outputs, `tf.ones((78,5))` is an appropriate value for the `targets` parameter for a regression task.

The obtained explanation is the some of the explanation for each one of the outputs.
