### ISSUE TITLE
InvalidArgumentError: TensorArray dtype is bfloat16 but Op is trying to write dtype float32 

### ISSUE THREAD

**Issue by krishnaadithya** [deel-ai/xplique#155]
I get this error while making this into Gradcam. 

I was trying to do gradcam on our pretrained model based model but it kept throwing "Stop Iteration" error. 

It was because the model graph was disconnected (Graph disconnected Exception), once I did fix that everything works except for gradcam.

**Comment by AntoninPoche** [comment]
Dear @krishnaadithya, I cannot give you a precise answer without more elements like the error log.

Nonetheless, in my view, two sources could cause your error:
- First, `GradCAM` manipulates the gradient inside the model. Therefore, this method is much more sensible to varying architecture.
- The other possibility comes from the error message. The error suggests a conflict between types; the Xplique library makes all its computations in `tf.float32`, which may conflict with the type of the weights inside your model.

I cannot provide you a quick fix, there are many cases where `GradCAM` cannot be applied.

Best regards
