### ISSUE TITLE
[Question] Concept Attribution from the Holistic paper

### ISSUE THREAD

**Issue by skumar-ml** [deel-ai/xplique#161]
I'm interested in implementing some of the Concept Attribution Methods (CATs) from the [Holistic](https://arxiv.org/pdf/2306.07304) paper. Do y'all have any recommendations on how one could adapt Xplique's other attribution methods to apply to concept vectors?

I was looking through the documentation/codebase and could only find the implementation of [Sobol indices in CRAFT's class](https://github.com/deel-ai/xplique/blob/master/xplique/concepts/craft.py#L295), but I'm guessing that the authors of the Holistic paper used the Xplique toolbox to implement the remainder of the CATs analyzed in the paper.

**Comment by AntoninPoche** [comment]
Dear @skumar-ml,

Thank you for your interest in the Holistic paper and the Xplique library. You can indeed use the Xplique library to compute the Concept Attribution Methods from Holistic.

If we take the notations from the paper, the CATs are attribution methods used to find the important concepts for a given prediction or on average. You can consider the multiplication by W and the g part of the model as a model working on tabular data. Thus, if you provide this model to Xplique, you will obtain decision-wise attributions. You just have to take the average of these attributions for a given predicted class to obtain global class attributions. You can take a look at [the tutorial on tabular data](https://colab.research.google.com/drive/1h0lThbcP5d2VKtRxwLG8z7KC8PExcVIA) or at [the documentation on attribution methods](https://deel-ai.github.io/xplique/latest/api/attributions/api_attributions/) to see which are the requirements for these methods.

Finally, if you are interested in concept methods, I want to highlight that such methods are directly implemented in the library. You will find a description of the `Craft` method API on [the corresponding documentation page](https://deel-ai.github.io/xplique/latest/api/concepts/craft/). Note that tutorials are available for both PyTorch and TensorFlow.

Best regards,
Antonin
