### ISSUE TITLE
Clarification on Magnitude Computation in MACO Implementation 

### ISSUE THREAD

**Issue by sushmanthreddy** [deel-ai/xplique#168]
Hello @lucashervier and @Agustin-Picard ,  

First of all, thank you for sharing your insightful work on the MACO technique, as detailed in the paper *"Unlocking Feature Visualization for Deeper Networks with Magnitude Constrained Optimization (MACO)."* I have been exploring your methodology and trying to replicate the results, but I am facing some challenges with understanding a specific aspect of the implementation.  

In the paper, it is mentioned that the phase spectrum is optimized while the magnitude spectrum is kept constant, derived from an `.npy` file. I would appreciate it if you could provide more details or code snippets regarding:  

1. The process used to compute the magnitude spectrum.  
2. How the magnitude values were stored in the `.npy` file and any preprocessing steps involved.  
3. Any references or helper scripts that could assist in extracting the magnitude spectrum for use in the MACO implementation.  

This clarification would be incredibly helpful for replicating and applying the technique to other datasets.  

Thank you in advance for your help!

**Comment by Agustin-Picard** [comment]
Hi @sushmanthreddy,

1. The code used to compute the spectrum is implemented in the function `init_maco_buffer` in `xplique.feature_visualization.preconditioning` Ln 239. It essentially computes the `rfft2d` (so, the real part of the FFT in 2 dimensions) per channel (3 in RGB, 1 in grayscale), applies the absolute value, and calculates the mean over the dataset. This is pretty typical and computes the magnitude of the spectrum. The `moveaxis`/`transpose` are used to ensure compatibility between the input shape and the FFT functions.
2. @fel-thomas will correct me if I'm wrong but this `.npy` is simply the result of an `np.save` of the array that comes out of the previous computation.
3. Just use the `init_maco_buffer` function, it should do the trick ;)

There's also another implementation (also by @fel-thomas) that you can use if you prefer to use PyTorch: https://github.com/[serre-lab/Horama](https://github.com/serre-lab/Horama)

Don't hesitate if you need further clarification.
