### ISSUE TITLE
Handle model with tensor that has channel first

### ISSUE THREAD

**Issue by AdrienGauffriau** [deel-ai/xplique#66]
The explaination does not work for models that ask for the channel as the first dimension of the input tensor (channel, height, width.
When such a model is provided, the output shape of the explanation is (channel x height) instead of (height x width)

**Comment by lucashervier** [comment]
Hi Adrien!

Would a wrapper such as the one used in this [example](https://deel-ai.github.io/xplique/callable.html) fix it ?
