### ISSUE TITLE
Fidelity Metrics with tabular values

### ISSUE THREAD

**Issue by dv-ai** [deel-ai/xplique#72]
Tabular values models are not supported by fidelity metrics.

**Comment by DavidPetiteau** [comment]
The fidelity metrics (Deletion and Insertion) are implemented

**Comment by lucashervier** [comment]
@DavidPetiteau where are we on this issue ? Has any PR solve this ?

**Comment by DavidPetiteau** [comment]
I succesfully pushed a new version with data tabular causal metrics

but before that, I wrote on the develop branch directly on the github (very bad idea), so the branch is upside down
I don't know how to close this issue properly

**Comment by DavidPetiteau** [comment]
before tomorrow evening, I didn't have the rights to push anything on this github

**Comment by lucashervier** [comment]
As I see it you try to solve this issue with the PR #88 ? Can you please:
- Make the change to your code so the workflows pass (linting issue)
- Edit your PR message to mention all the related issues you are trying to solve ?
