### ISSUE TITLE
Time Series explanation visualization

### ISSUE THREAD

**Issue by AntoninPoche** [deel-ai/xplique#73]
Add the means to make visualization of time series explanations.

**Comment by lucashervier** [comment]
Any progress on this issue yet ?

**Comment by AntoninPoche** [comment]
Draft functions are used for Confiance, but nothing clean yet.

**Comment by lucashervier** [comment]
Do you think it is possible to add such visualization functions in your PR #84 in order to have them for the first Tagged Version ? It does not need to have full functionnality yet and we can improve it later but at least have a minimal function based on your drafts functions ?

**Comment by AntoninPoche** [comment]
It will depend on the deadline for the first tagged version and my disponibilities, I cannot be 100% sure.
