### ISSUE TITLE
Fidelity evolution curve visualization

### ISSUE THREAD

**Issue by AntoninPoche** [deel-ai/xplique#74]
The insertion and deletion metrics were added a detailed_evaluate() method, this method returns the score on the different perturbed input. This output can be used to make the evolution curves for insertion and deletion.

Those curves possess more information than the usually used auc.

This visualization should support the plot of several curves on the same graphic so that explanation methods can be compared.

**Comment by fel-thomas** [comment]
Done in #70, super cool work @AntoninPoche ! ;)
