### ISSUE TITLE
Warning appearing while calling some tabular visualization functions

### ISSUE THREAD

**Issue by DavidPetiteau** [deel-ai/xplique#87]
A warning appears when calling the explanation visualization functions plot_feature_impact and plot_mean_feature_impact.
The problem is that the warning appears when calling the virtualization of each explanation..

It can be solved by adding the line in the python file xplique/plots/tabular.py (in the function plot_feature_impact): 
                axes.set_ylabel('')
This line can be added at the line 202 of the python file.

**Comment by lucashervier** [comment]
Nice catch! Can you please fix your PR issues, edit the PR message and mentions the related issues ?
