### ISSUE TITLE
Contribution: Add a protocol to raise issues

### ISSUE THREAD

**Issue by lucashervier** [deel-ai/xplique#89]
It would be a good practice to have a template when people submit issues. It could even be different template depending on the issue: do we need to reproduce the error, should we have the machine configuration, is it a comfort issue (e.g I can have a hotfix but it would be a nice enhancement that I do not use it), etc....

@justinplakoo do you have any idea how we should manage that ? I think we can add an issue template, what do you think ?

**Comment by justinplakoo** [comment]
I think it would be a good solution to add a generic issue template...

**Comment by fel-thomas** [comment]
Agree with Justin, I think indeed that it may be time to implement it

**Comment by lucashervier** [comment]
Look at #90 ;)
